=== freebsd/freebsd-doc/fr/events/events.dtd
<!-- Copyright (c) 2003 Simon L. Nielsen <simon@FreeBSD.org>
     All rights reserved.

     Redistribution and use in source and binary forms, with or without
     modification, are permitted provided that the following conditions
     are met:
     1. Redistributions of source code must retain the above copyright
	notice, this list of conditions and the following disclaimer.
     2. Redistributions in binary form must reproduce the above copyright
	notice, this list of conditions and the following disclaimer in the
	documentation and/or other materials provided with the distribution.

     THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
     IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
     ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
     FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
     DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
     OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
     LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
     OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
     SUCH DAMAGE.

     $FreeBSD$
-->

<!-- 
   The FreeBSD French Documentation Project
   Original revision: 1.1
-->

<!-- DTD for events.xml on the FreeBSD website. -->

<!ELEMENT events (cvs:keywords?, event+)>

<!ELEMENT event (name?, url?, startdate, enddate, location, description?, link*)>
<!ATTLIST event id ID #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!--
     Meaning of type attribute:
       freebsd-website:
	 The URL is relative to the FreeBSD website root.
	 The URL should start with a single "/".
       absolute:
	 Normal absolute URL.
-->
<!ATTLIST url type (absolute|freebsd-website) "absolute">

<!ELEMENT startdate (year,month,day)>
<!ELEMENT enddate (year,month,day)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>

<!ELEMENT location (country?,state?,city?,site?,address?)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT site (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT description (#PCDATA|a|tt|i|b)*>

<!-- Misc HTML entities which might be used; just add more as needed -->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT b (#PCDATA|a)*>
<!ELEMENT i (#PCDATA|a)*>
<!ELEMENT tt (#PCDATA|a)*>

<!--
     Link to a web page (local or remote) with additional information
     about the event.  Can also be used for post-event comments/notes.
-->
<!ELEMENT link (name, url)>
<!ATTLIST link type (photos|notes|other) "other">

<!-- Common CVS tags -->
<!ELEMENT cvs:keywords (cvs:keyword+)>
<!ATTLIST cvs:keywords xmlns:cvs CDATA #FIXED 'http://www.FreeBSD.org/XML/CVS'>
<!ATTLIST cvs:keywords version CDATA #FIXED '1.0'>

<!ELEMENT cvs:keyword (#PCDATA)>
<!ATTLIST cvs:keyword name CDATA #REQUIRED>

=== freebsd/freebsd-doc/ru_RU.KOI8-R/share/xml/events2008.xml
<?xml version="1.0" encoding="koi8-r"?>
<!DOCTYPE events PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for Events//EN"
                        "http://www.FreeBSD.org/XML/share/xml/events.dtd">
<!--
     The FreeBSD Russian Documentation Project

     $FreeBSDru: frdp/www/ru/events/events.xml,v 1.5 2005/06/18 09:56:15 andy Exp $

     Original revision: 1.1
-->
<!--
     События, которые могут представлять интерес для пользователей FreeBSD.

     Пожалуйста, сортируйте мероприятия по дате начала.
-->

<events>
    <cvs:keyword xmlns:cvs="http://www.FreeBSD.org/XML/CVS">
      $FreeBSD$
    </cvs:keyword>

  <event id="nllgg-2008">
    <name>NLLGG-bijeenkomst december 2008</name>
    <url>http://www.nllgg.nl/bijeenkomst_20081213</url>
    <startdate>
      <year>2008</year>
      <month>12</month>
      <day>13</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>12</month>
      <day>13</day>
    </enddate>
    <location>
      <country code="NL">Нидерланды</country>
      <state>Utrecht</state>
      <city>Utrecht</city>
      <site>Liefland college</site>
    </location>

    <description>The "Nederlandse Linux Gebruikers Groep" (NLLGG)
      organisation is arranging a national community day in Utrecht
      focussing on BSD.  Robert Watson, Hans vd Looy, Marten Vijn,
      Wim Vandeputte and Remko Lodder will do presentations for the
      Linux community.</description>
  </event>

  <event id="meetbsd-2008">
    <name>MeetBSD California 2008</name>
    <url>http://meetbsd.com/</url>
    <startdate>
      <year>2008</year>
      <month>11</month>
      <day>15</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>11</month>
      <day>16</day>
    </enddate>
    <location>
      <country code="US">США</country>
      <state>California</state>
      <city>Mountain View</city>
      <site>Googleplex</site>
    </location>

    <description>meetBSD was started in Krakow, Poland in 2004 and
      strong turnout and highly regarded technical presentations have
      allowed it to continue each year since then.  meetBSD is a
      conference devoted to the BSD operating systems with a strong
      emphasis towards FreeBSD.  meetBSD 2007 was held in Warsaw,
      Poland and will continue this year in Mountain View, California.
      This year marks the first meetBSD held in California, so join us
      to celebrate FreeBSD's 15th Anniversary!</description>
  </event>

  <event id="ticino-2008">
    <name>Ticino Informatica 2008</name>
    <startdate>
      <year>2008</year>
      <month>10</month>
      <day>22</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>10</month>
      <day>25</day>
    </enddate>
    <location>
      <country code="CH">Швейцария</country>
      <city>Lugano</city>
      <site>Palazzo dei Congressi</site>
    </location>
    <description>FreeBSD and The FreeBSD Foundation
      Stand A13 Presented by OEMS Sagl</description>
  </event>

  <event id="eurobsdcon-2008">
    <name>EuroBSDCon 2008</name>
    <url>http://2008.eurobsdcon.org/</url>
    <startdate>
      <year>2008</year>
      <month>10</month>
      <day>18</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>10</month>
      <day>19</day>
    </enddate>
    <location>
      <country code="FR">Франция</country>
      <city>Strasbourg</city>
      <site>University of Strasbourg</site>
    </location>
    <description>The seventh annual European BSD Conference.  It is
      oriented to developers and users of all BSD flavors, including
      FreeBSD of course.  A variety of full and half-day tutorials will
      precede the conference.</description>
  </event>

  <event id="nycbsdcon-2008">
    <name>NYCBSDCon 2008</name>
    <url>http://www.nycbsdcon.org/</url>
    <startdate>
      <year>2008</year>
      <month>10</month>
      <day>11</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>10</month>
      <day>12</day>
    </enddate>
    <location>
      <country code="US">США</country>
      <city>New York City</city>
      <site>Columbia University</site>
    </location>
    <description>The New York City *BSD Conference (NYCBSDCon) 2008
      will be held at Columbia University in Manhattan.  NYCBSDCon is
      the main technical conference on the East Coast for the BSD
      community to get together to share and gain knowledge, to
      network with like-minded people, and to have fun. This event is
      organized by members of the New York City *BSD Users Group
      (NYC*BUG).</description>
  </event>

  <event id="openexpo-2008">
    <name>OpenExpo 2008</name>
    <url>http://www.openexpo.ch/</url>
    <startdate>
      <year>2008</year>
      <month>9</month>
      <day>24</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>9</month>
      <day>25</day>
    </enddate>
    <location>
      <country code="CH">Швейцария</country>
      <city>Zurich</city>
    </location>
    <description>The goal of OpenExpo is the promotion of Open Source
      software in the business environment.  Among many others, there
      will be a FreeBSD booth.</description>
  </event>

  <event id="coscup-2008">
    <name>COSCUP 2008 - Conference for Open Source Coders, Users and Promoters</name>
    <url>http://coscup.org/2008/</url>
    <startdate>
      <year>2008</year>
      <month>8</month>
      <day>23</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>8</month>
      <day>24</day>
    </enddate>
    <location>
      <country code="TW">Тайвань</country>
      <city>Taipei</city>
      <site>International Conference Hall, Institute of Applied Mechanics,
	National Taiwan University</site>
    </location>
    <description>COSCUP 2008 is the 3rd incarnation of the series,
      and becomes the biggest annual open source community party in Taiwan.
      Several FreeBSD contributions will be presenting on FreeBSD topics.</description>
  </event>

  <event id="froscon-2008">
    <name>FrOSCon 2008</name>
    <url>http://www.froscon.org/</url>
    <startdate>
      <year>2008</year>
      <month>8</month>
      <day>23</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>8</month>
      <day>24</day>
    </enddate>
    <location>
      <country code="DE">Германия</country>
      <city>Sankt Augustin</city>
      <site>Fachhochschule Bonn-Rhein-Sieg</site>
      <address>Grantham-Allee 20</address>
    </location>
    <description>FrOSCon is a two day conference on Free Software
      and Open Source, taking place in Sankt Augustin near the cities
      of Bonn and Cologne.  The conference revolves around a rich schedule
      of talks, highlighting current topics in Free Software and Open
      Source.</description>
  </event>

  <event id="oscon-2008">
    <name>O'Reilly Open Source Conference 2008</name>
    <url>http://en.oreilly.com/oscon2008/public/content/home</url>
    <startdate>
      <year>2008</year>
      <month>7</month>
      <day>21</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>7</month>
      <day>25</day>
    </enddate>
    <location>
      <country code="US">США</country>
      <city>Portland, Oregon</city>
      <site>Oregon Convention Center</site>
    </location>

    <description>The annual O'Reilly Open Source Conference will again
      have a FreeBSD booth this year.  Matt Olander, Dru Lavigne, and
      others will help spread the word about FreeBSD.
    </description>
    <upcomingurl>http://upcoming.yahoo.com/event/430248/</upcomingurl>
  </event>

  <event id="lsm-2008">
    <name>9th Libre Software Meeting</name>
    <url>http://2008.rmll.info/?lang=en</url>
    <startdate>
      <year>2008</year>
      <month>7</month>
      <day>1</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>7</month>
      <day>5</day>
    </enddate>
    <location>
      <country code="FR">Франция</country>
      <city>Mont-de-Marsan</city>
      <site>Multiple Locations</site>
    </location>
    <description>The Libre Software Meeting has occurred each year
      since July 2000.  This year there will again be a FreeBSD boot
      camp to introduce new users to the Operating System.</description>
    <upcomingurl>http://upcoming.yahoo.com/event/685886/</upcomingurl>
  </event>

  <event id="linuxtag-2008">
    <name>LinuxTag 2008</name>
    <url>http://www.linuxtag.org/2008/en/</url>
    <startdate>
      <year>2008</year>
      <month>5</month>
      <day>28</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>5</month>
      <day>31</day>
    </enddate>
    <location>
      <country code="DE">Германия</country>
      <city>Berlin</city>
      <site>Messe Berlin</site>
    </location>
    <description>LinuxTag is Europe's largest event about Free
      Software, Linux and Open Source.  This year there will be the
      traditional FreeBSD booth and several BSD talks.  It will also be
      possible to take the BSDA certification exam there on Friday May
      30.</description>
  </event>

  <event id="bsdcan-2008">
    <name>BSDCan 2008</name>
    <url>http://www.bsdcan.org/2008/</url>
    <startdate>
      <year>2008</year>
      <month>5</month>
      <day>16</day>
    </startdate>
    <enddate>
      <year>2008</year>
      <month>5</month>
      <day>17</day>
    </enddate>
    <location>
      <country code="CA">Канада</country>
      <city>Ottawa</city>
      <site>University of Ottawa</site>
    </location>
    <description>BSDCan - это конференция разработчиков с сильной ориентацией
      на передовые технологии, исследовательские проекты и находящиеся в
      разработке идеи.  На ней также представлены инфраструктурные
      пользовательские проекты, к участию приглашаются разработчики
      как свободного программного обеспечения, так и коммерческих
      продуктов.</description>
  </event>

  <event id="bsdcon-barcelona-2008">
    <name>BSDCon Barcelona 2008</name>
