=== freebsd/freebsd-doc/share/sgml/gallery.dtd
<!-- DTD for commercial gallery entries on the FreeBSD website. -->
<!-- $FreeBSD$ -->

<!ENTITY % xml.features "INCLUDE">
<!ENTITY % sgml.features "IGNORE">

<!ELEMENT entries (cvs:keywords?, categories?, entry+)>

<!ELEMENT categories (category)+>
<!ATTLIST categories
  id		ID	#IMPLIED
>

<!ELEMENT category (#PCDATA)>
<!ATTLIST category
  id		ID	#IMPLIED
>

<!ELEMENT entry (name, url?, description)>
<!ATTLIST entry
  id		CDATA	#REQUIRED
  category	CDATA	#IMPLIED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT description (#PCDATA|a|b|br|i|tt|em|p|strong|img|ul)*>

<!-- misc HTML tags -->
<!ELEMENT a (#PCDATA|img)*>
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT b (#PCDATA|a)*>
<!ELEMENT br (#PCDATA|a)*>
<!ELEMENT i (#PCDATA|a)*>
<!ELEMENT tt (#PCDATA|a)*>
<!ELEMENT em (#PCDATA|a)*>
<!ELEMENT p (#PCDATA|a)*>
<!ELEMENT strong (#PCDATA|a)*>
<!ELEMENT ul (li)*>
<!ELEMENT li (#PCDATA|a)*>
<!ELEMENT img (#PCDATA|a)*>
<!ATTLIST img alt CDATA #IMPLIED>
<!ATTLIST img src CDATA #REQUIRED>

<!-- common cvs tags -->
<!ELEMENT cvs:keywords (cvs:keyword+)>
<!ATTLIST cvs:keywords xmlns:cvs CDATA #FIXED 'http://www.FreeBSD.org/XML/CVS'>
<!ATTLIST cvs:keywords version CDATA #FIXED '1.0'>

<!ELEMENT cvs:keyword (#PCDATA)>
<!ATTLIST cvs:keyword name CDATA #REQUIRED>

<!ENTITY % autogen.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Automatically Generated Entities//EN"
        "http://www.FreeBSD.org/XML/cwd/autogen.ent">
%autogen.ent;

<!ENTITY % iso8879.ent
 PUBLIC "-//FreeBSD//ENTITIES ISO 8879:1986 Entity Set//EN//XML"
        "http://www.FreeBSD.org/XML/www/share/sgml/iso8879.ent">
%iso8879.ent;

<!ENTITY % l10n.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Entities//EN"
        "http://www.FreeBSD.org/XML/www/share/sgml/l10n.ent">
%l10n.ent;

<!ENTITY % common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Common Entities//EN"
        "http://www.FreeBSD.org/XML/www/share/sgml/common.ent">
%common.ent;

=== freebsd/freebsd-doc/share/sgml/commercial.misc.xml
<?xml version="1.0"?>
<!DOCTYPE entries PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for Commercial Gallery//EN"
                         "http://www.FreeBSD.org/XML/www/share/sgml/gallery.dtd">
<!-- $FreeBSD$ -->

<entries>
  <cvs:keywords xmlns:cvs="http://www.FreeBSD.org/XML/CVS" version="1.0">
    <cvs:keyword name="freebsd">
      $FreeBSD$
    </cvs:keyword>
  </cvs:keywords>

  <entry id="FreeBSDMall">
    <name>FreeBSD Mall</name>
    <url>http://www.freebsdmall.com/</url>
    <description>
      The FreeBSD Mall can provide everything you may want or need to
      enhance your FreeBSD experience. Are you new to FreeBSD? Or, perhaps
      you've been using it for years? We have something for you. We have
      the latest FreeBSD CDROMs, helpful books, and colorful shirts and
      hats. Stay current with FreeBSD and put it to work for you!
    </description>
  </entry>

  <entry id="ScotGold">
    <name>ScotGold Products</name>
    <url>http://www.scotgold.com/acatalog/ScotGold_Catalogue_BSD_Daemon_Stuff_3.html</url>
    <description>
      ScotGold Products design and manufacture PC case badges, including a
      BSD daemon badge with the permission and blessing of Kirk McKusick.
    </description>
  </entry>

  <entry id="exavault">
    <name>ExaVault</name>
    <url>http://www.exavault.com</url>
    <description>
      ExaVault provides inexpensive online remote backup space that is
      accessible via open, industry standard protocols, including rsync,
      FTP and SFTP.  It is ideal for small and medium businesses, web
      hosting companies and others that need a quick, transparent,
      maintenance-free way of mirroring a copy of their data to a remote
      backup server.  We are fully FreeBSD compatible, and provide full
      support for getting things setup on your FreeBSD system. 
    </description>
  </entry>

  <entry id="gfuschulung">
    <name>GFU Schulung</name>
    <url>http://www.gfu.net/</url>
    <description>
      GFU offers
      <a href="http://www.gfu.net/seminare-schulungen-kurse/oracle_db_sprachen_design_sk38/freebsd_training_s856.html">FreeBSD Training</a>
      for customizing servers with a whole bunch of open source software
      like PostgreSQL, OpenOffice, Cyrus IMAP, etc.
      Upon customer request especially:
      <a href="http://www.gfu.net/seminare-schulungen-kurse/oracle_db_sprachen_design_sk38/oracle_unter_freebsd_s854.html">Oracle Administration under FreeBSD</a>.
    </description>
  </entry>
</entries>
