=== freebsd/freebsd-doc/share/sgml/news.dtd
<!-- $FreeBSD$ -->

<!ENTITY % xml.features "INCLUDE">
<!ENTITY % sgml.features "IGNORE">
<!ENTITY lists 'http://lists.freebsd.org/pipermail'>
<!ENTITY lists.stable '&lists;/freebsd-stable'>

<!ELEMENT news (cvs:keywords?, year)+>

<!ELEMENT cvs:keywords (cvs:keyword+)>
<!ATTLIST cvs:keywords xmlns:cvs CDATA #FIXED 'http://www.FreeBSD.org/XML/CVS'>
<!ATTLIST cvs:keywords version CDATA #FIXED '1.0'>

<!ELEMENT cvs:keyword (#PCDATA)>
<!ATTLIST cvs:keyword name CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  id		ID	#IMPLIED
>

<!ELEMENT year (name, (month)+)>
<!ATTLIST year
  id		ID	#IMPLIED
>

<!ELEMENT month (name, (day)+)>
<!ATTLIST month
  id		ID	#IMPLIED
>

<!ELEMENT day (name, (event)+)>
<!ATTLIST day
  id		ID	#IMPLIED
>

<!ELEMENT event ((title)?, (p)+)>
<!ATTLIST event
  id		ID	#IMPLIED
>

<!ELEMENT title (#PCDATA | a)*>
<!ATTLIST title
  id		ID	#IMPLIED
>

<!ELEMENT p (#PCDATA | a | i)*>
<!ATTLIST p
  id		ID	#IMPLIED
>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
  id		ID	#IMPLIED
  href		CDATA	#REQUIRED
>

<!ELEMENT i (#PCDATA)>
<!ATTLIST i
  id		ID	#IMPLIED
>

<!ENTITY % autogen.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Automatically Generated Entities//EN"
        "http://www.FreeBSD.org/XML/cwd/autogen.ent">
%autogen.ent;

<!ENTITY % iso8879.ent
 PUBLIC "-//FreeBSD//ENTITIES ISO 8879:1986 Entity Set//EN//XML"
        "http://www.FreeBSD.org/XML/www/share/sgml/iso8879.ent">
%iso8879.ent;

<!ENTITY % l10n.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Entities//EN"
        "http://www.FreeBSD.org/XML/www/lang/share/sgml/l10n.ent">
%l10n.ent;

<!ENTITY % l10n-common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Common Entities//EN"
        "http://www.FreeBSD.org/XML/www/share/sgml/l10n.ent">
%l10n-common.ent;

<!ENTITY % common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Common Entities//EN"
        "common.ent">
%common.ent;

=== freebsd/freebsd-doc/de_DE.ISO8859-1/htdocs/news/2008/news.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE news PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for News//EN"
                      "http://www.FreeBSD.org/XML/www/share/sgml/news.dtd">
<!--
     $FreeBSD$
     $FreeBSDde: de-www/news/2008/news.xml,v 1.2 2010/07/17 12:21:31 jkois Exp $
     basiert auf: 1.224
-->

<!-- Simple schema for FreeBSD Project news.

     Divide time in to <year>, <month>, and <day> elements, each of which
     has a <name>.

     each <day> element contains one or more <event> elements.

     Each <event> contains an optional <title>, and then a <p>.  <p> elements
     can contain <a> anchors.  Within the "href" attribute of the anchor
     &base; or &enbase; will be replaced with the base URI necessary to reach the FreeBSD
     document root, and should always be used to start URLs at www.FreeBSD.org
     or one of the mirrors.

     Use the <title> element if the <p> content is lengthy.  When generating
     synopses of this information (e.g., for syndication using RDF files),
     the contents of <title> will be preferred over <p>.

     *** Former Summer of Code Students: Please note that you are an
         SoC alumnus when you add your new committer announcement.
         Also, don't feel shy to add more information about what you
         would like to work on.  ***
-->

<news>
  <cvs:keywords xmlns:cvs="http://www.FreeBSD.org/XML/CVS" version="1.0">
    <cvs:keyword name="freebsd">
      $FreeBSD$
    </cvs:keyword>
  </cvs:keywords>

  <year>
    <name>2008</name>

    <month>
      <name>12</name>

      <day>
	<name>25</name>

	<event>
	  <title>&os; 7.1-RC2 verf&#252;gbar</title>

	  <p>Der zweite (und letzte) Release Candidate von &os;&#160;7.1 ist nun <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2008-December/047203.html">verf&#252;gbar</a>.
	    ISO-Images f&#252;r alle Tier-1-Architekturen finden Sie auf den
	    <a href="&enbase;/doc/de_DE.ISO8859-1/books/handbook/mirrors-ftp.html">
	    &os;-Spiegelservern</a>.</p>
	</event>
      </day>

      <day>
	<name>23</name>

	<event>
	  <title>&os; Foundation Newsletter Dezember 2008</title>

	  <p>Die &os; Foundation hat ihren <a
	    href="http://www.freebsdfoundation.org/press/2008Dec-newsletter.shtml">
	    Newsletter f&#252;r Dezember 2008</a> ver&#246;ffentlicht, in dem sie
	    beschreibt, wie sie das &os; Project und die &os;-Gemeinde bisher
	    unterst&#252;tzt hat.</p>
	</event>
      </day>

      <day>
	<name>9</name>

	<event>
	  <title>&os; 7.1-RC1 verf&#252;gbar</title>

	  <p>Der erste Release Candidate von &os;&#160;7.1 ist nun <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2008-December/047014.html">verf&#252;gbar</a>.
	    ISO-Images f&#252;r alle Tier-1-Architekturen finden Sie auf den
	    <a href="&enbase;/doc/de_DE.ISO8859-1/books/handbook/mirrors-ftp.html">
	    &os;-Spiegelservern</a>.</p>
	</event>
      </day>

      <day>
	<name>3</name>

	<event>
	  <title>Neuer BSD-Channel auf YouTube</title>

	  <p>Wir freuen uns, bekanntgeben zu d&#252;rfen, dass wir ab sofort
	    &#252;ber einen dezidierten YouTube-Channel verf&#252;gen,
	    &#252;ber den wir Videos zu technischen Vortr&#228;gen zu
	    FreeBSD und anderen BSD-Betriebssystemen anbieten k&#246;nnen.
	    Dieser Channel ist unter der Adresse <a
	    href="http://www.youtube.com/bsdconferences">www.youtube.com/bsdconferences</a>
	    erreichbar.</p>

	  <p>Dieser Channel erlaubt es uns, komplette Vortr&#228;ge von
	    FreeBSD-Konferenzen zu ver&#246;ffentlichen.  Die ersten vier
	    Videos, die von Julian Elisher auf der <a
	    href="http://www.meetbsd.com">MeetBSD</a>-Konferenz aufgezeichnet
	    wurden, sind bereits online.  Weitere Videos werden in K&#252;rze
	    verf&#252;gbar sein.</p>
	</event>
      </day>
    </month>

    <month>
      <name>11</name>

      <day>
	<name>28</name>

	<event>
	  <title>FreeBSD 6.4-RELEASE verf&#252;gbar</title>

	  <p><a href="&enbase;/releases/6.4R/announce.html">FreeBSD
	    6.4-RELEASE</a> ist ab sofort verf&#252;gbar.  Lesen Sie
	    bitte vor der Installation die <a
	    href="&enbase;/releases/6.4R/errata.html">Release Errata</a>,
	    um sich &#252;ber aktuelle Neuigkeiten und/oder eventuelle
	    Probleme im Umgang mit FreeBSD 6.4 zu informieren.  Weitere
	    Informationen zu verschiedenen FreeBSD-Versionen finden Sie
	    auf der Seite <a
	    href="&base;/releases/index.html">Release Information</a>.</p>
	</event>
      </day>

      <day>
	<name>18</name>

	<event>
	  <p>Reaktiviertes Commit-Bit: <a
	    href="mailto:pho@FreeBSD.org">Peter Holm</a> (src)</p>
	</event>
      </day>

      <day>
	<name>16</name>

	<event>
	  <title>Offizielles FreeBSD-Forum gestartet</title>

	  <p>Das FreeBSD Project freut sich, bekanntgeben zu d&#252;rfen, dass
	    wir nach umfangreichen Vorarbeiten unser offizielles, auf FreeBSD
	    basierendes Diskussionforum gestartet haben.  Wir hoffen, dass
	    dieses &#246;ffentliche Forum (ebenso wie unsere Mailinglisten) dazu
	    beitragen wird, unsere Anwender bei Ihrer Arbeit mit FreeBSD zu
	    unterst&#252;tzen.</p>

	  <p>Um sich zu registrieren und/oder unser Forum zu benutzen, rufen Sie
	    bitte die Internetseite <a
	    href="http://forums.FreeBSD.org">http://forums.FreeBSD.org</a> auf.</p>
	</event>
      </day>

      <day>
	<name>10</name>

	<event>
	  <title>Statusbericht Juli - September 2008</title>

	  <p>Der Statusbericht f&#252;r die Monate Juli - September 2008
	    mit 14 Eintr&#228;gen ist <a
	    href="&enbase;/news/status/report-2008-07-2008-09.html">
	    verf&#252;gbar</a>.</p>
	</event>
      </day>

      <day>
	<name>3</name>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:rene@FreeBSD.org">Ren&eacute; Ladan</a> (doc-nl)</p>
	</event>

	<event>
	  <title>FreeBSD 6-4-RC2 verf&#252;gbar</title>

	  <p>Der zweite Release Candidate von FreeBSD 6.4 ist <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2008-November/046364.html">verf&#252;gbar</a>.
	    ISO-Images f&#252;r alle Tier-1-Architekturen finden Sie auf den
	    <a href="&enbase;/doc/de_DE.ISO8859-1/books/handbook/mirrors-ftp.html">
	    &os;-Spiegelservern.</a>.  Es handelt sich dabei
	    voraussichtlich um die letzte Testversion vor der
	    Ver&#246;ffentlichung von FreeBSD 6.4, daher bitten wir alle,
	    diese Version zu testen und eventuell auftretende Fehler und
	    Probleme umgehend zu melden.</p>
	</event>
      </day>

      <day>
	<name>1</name>

	<event>
	  <title>Neuer Committer: <a
	    href="mailto:versus@FreeBSD.org">Konrad Jankowski</a> (src).
	    Ein SoC2008-Teilnehmer.</title>

	  <p>Konrad nahm am <a
	    href="http://code.google.com/soc">Summer Of Code 2008</a> teil.
	    Er wird seine Arbeit im i18n-Bereich beginnen und insbesondere
	    seinen SoC-Code in die n&#228;chsten FreeBSD-Versionen
	    integrieren.</p>
	</event>
      </day>
    </month>

    <month>
      <name>10</name>

      <day>
	<name>19</name>

	<event>
	  <title>&os; 7.1-BETA2 verf&#252;gbar</title>

	  <p>Die zweite Betaversion von &os;&#160;7.1 ist nun <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2008-October/046037.html">verf&#252;gbar</a>.
	    ISO-Images f&#252;r alle Tier-1-Architekturen finden Sie auf den
	    <a href="&enbase;/doc/de_DE.ISO8859-1/books/handbook/mirrors-ftp.html">
	    &os;-Spiegelservern</a>.</p>
	</event>
      </day>

      <day>
	<name>12</name>

	<event>
	  <title>FreeBSD 6-4-RC1 verf&#252;gbar</title>

	  <p>Der erste Release Candidate von FreeBSD 6.4 is <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2008-October/045869.html">verf&#252;gbar</a>.
	    ISO-Images f&#252;r alle Tier-1-Architekturen finden Sie auf den
	    <a href="&enbase;/doc/de_DE.ISO8859-1/books/handbook/mirrors-ftp.html">
	    &os;-Spiegelservern.</a>.</p>
	</event>
      </day>

      <day>
	<name>6</name>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:lstewart@FreeBSD.org">Lawrence Stewart</a> (src)</p>
	</event>
      </day>
    </month>

    <month>
      <name>9</name>

      <day>
	<name>18</name>

	<event>
	  <title>Summer of Code-Projekte abgeschlossen</title>

	  <p>Wir freuen uns, bekanntgeben zu d&#252;rfen, dass 19
	    Studenten Ihre FreeBSD-Projekte im Rahmen von Google's
	    <a href="&enbase;/projects/summerofcode-2008.html">Summer
	    of Code</a> erfolgreich abgeschlossen haben.  Wir
	    gratulieren den Studenten und ihren Mentoren und danken
	    <a href="http://www.google.com/">Google</a> f&#252;r die
	    Schaffung und Finanzierung dieses Programms.</p>
	</event>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:zec@FreeBSD.org">Marko Zec</a> (src)</p>
	</event>
      </day>

      <day>
	<name>15</name>

	<event>
  	  <title>PC-BSD 7 ist verf&#252;gbar</title>

	  <p>PC-BSD 7 ist erschienen.  Bei PC-BSD handelt es sich um ein
	    erfolgreiches Desktop-Betriebssystem, das auf FreeBSD basiert
	    sich darauf konzentriert, eine einfach zu benutzende
	    Arbeitsumgebung bereitzustellen.  Die neue Version kann
	    <a href="http://www.pcbsd.org">heruntergeladen</a> oder als
	    DVD <a href="http://www.freebsdmall.com">gekauft</a> werden.</p>
	</event>

	<event>
	  <p>Neuer Committer: <a
	    href="mailto:rnoland@FreeBSD.org">Robert Noland</a> (src)</p>
	</event>
      </day>

      <day>
	<name>13</name>

	<event>
	  <title>&os; 6.4-BETA/7.1-BETA sind verf&#252;gbar</title>

	  <p>Die ersten Beta-Versionen von &os;-6.4 und &os;-7.1 sind
	    verf&#252;gbar.  ISO-Images f&#252;r alle
	    Tier-1-Architekturen k&#246;nnen <a
	    href="http://lists.freebsd.org/pipermail/freebsd-stable/2008-September/045016.html">ab
	    sofort</a> von den meisten <a
	    href="&url.doc.base-en;/books/handbook/mirrors-ftp.html">&os;-Spiegelservern</a>
	    heruntergeladen werden.  Wir bitten alle, diese Versionen zu
	    testen und eventuell auftretende Fehler zu melden.  Weitere
	    Informationen zu diesen &os;-Versionen finden Sie auf der Seite
