=== freebsd/freebsd-doc/share/sgml/press.dtd
<!-- $FreeBSD$ -->

<!ENTITY % xml.features "INCLUDE">
<!ENTITY % sgml.features "IGNORE">

<!ELEMENT press (cvs:keywords?, year)+>

<!ELEMENT cvs:keywords (cvs:keyword+)>
<!ATTLIST cvs:keywords xmlns:cvs CDATA #FIXED 'http://www.FreeBSD.org/XML/CVS'>
<!ATTLIST cvs:keywords version CDATA #FIXED '1.0'>

<!ELEMENT cvs:keyword (#PCDATA)>
<!ATTLIST cvs:keyword name CDATA #REQUIRED>

<!ELEMENT year (name, (month)+)>
<!ATTLIST year
  id		ID	#IMPLIED
>

<!ELEMENT month (name, (story)+)>
<!ATTLIST month
  id		ID	#IMPLIED
>

<!ELEMENT story (name, url, site-name, site-url, date, author, (p)+)>
<!ATTLIST storyevent
  id		ID	#IMPLIED
>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  id		ID	#IMPLIED
>
<!ELEMENT url (#PCDATA)>
<!ATTLIST url
  id		ID	#IMPLIED
>
<!ELEMENT site-name (#PCDATA)>
<!ATTLIST site-name
  id		ID	#IMPLIED
>
<!ELEMENT site-url (#PCDATA)>
<!ATTLIST site-url
  id		ID	#IMPLIED
>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date
  id		ID	#IMPLIED
>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author
  id		ID	#IMPLIED
>

<!ELEMENT p (#PCDATA | a | tt)*>
<!ATTLIST p
  id		ID	#IMPLIED
>

<!ELEMENT tt (#PCDATA)>
<!ATTLIST tt
  id		ID	#IMPLIED
>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
  id		ID	#IMPLIED
  href		CDATA	#REQUIRED
>

<!ENTITY % autogen.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Automatically Generated Entities//EN"
        "http://www.FreeBSD.org/XML/cwd/autogen.ent">
%autogen.ent;

<!ENTITY % iso8879.ent
 PUBLIC "-//FreeBSD//ENTITIES ISO 8879:1986 Entity Set//EN//XML"
        "http://www.FreeBSD.org/XML/www/share/sgml/iso8879.ent">
%iso8879.ent;

<!ENTITY % l10n.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Entities//EN"
        "http://www.FreeBSD.org/XML/www/lang/share/sgml/l10n.ent">
%l10n.ent;

<!ENTITY % l10n-common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Common Entities//EN"
        "http://www.FreeBSD.org/XML/www/share/sgml/l10n.ent">
%l10n-common.ent;

<!ENTITY % common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Common Entities//EN"
        "common.ent">
%common.ent;

=== freebsd/freebsd-doc/en_US.ISO8859-1/htdocs/news/2008/press.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE press PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for Press//EN"
                      "http://www.FreeBSD.org/XML/share/xml/press.dtd">
<!--
 COMMITTERS PLEASE NOTE:
    News articles referenced in this file are also to be archived under
    "freefall:/c/www/bsddoc/press/".
-->
<press>
    <cvs:keyword xmlns:cvs="http://www.FreeBSD.org/XML/CVS">
      $FreeBSD$
    </cvs:keyword>

  <year>
    <name>2008</name>

    <month>
      <name>10</name>
      <story>
	<name>Review: PC-BSD 7</name>
	<url>http://www.osnews.com/story/20351/Review_PC-BSD_7</url>
	<site-name>OS News</site-name>
	<site-url>http://www.osnews.com/</site-url>
	<date>02 October 2008</date>
	<author>Amjith Ramanujam</author>
	<p>A review of PC-BSD 7.</p>
      </story>
    </month>

    <month>
      <name>8</name>
      <story>
	<name>Network-Attached Storage on the Cheap</name>
	<url>http://www.washingtonpost.com/wp-dyn/content/article/2008/08/26/AR2008082600237.html</url>
	<site-name>Washington Post</site-name>
	<site-url>http://www.washingtonpost.com/</site-url>
	<date>27 August 2008</date>
	<author>Tom Mainelli</author>
	<p>FreeBSD based FreeNAS is recommended for turning an old PC
	  into a storage appliance.</p>
      </story>

      <story>
	<name>How Do Open Source Installations Compare by Operating System?</name>
	<url>https://www.osscensus.org/newsletter/Census-News-August-2008.html</url>
	<site-name>The Open-Source Census</site-name>
	<site-url>http://www.osscensus.org/</site-url>
	<date>August 2008</date>
	<author>Stormy Peters</author>
	<p>A recent census shows interesting data about FreeBSD use.</p>
      </story>
    </month>

    <month>
      <name>7</name>
      <story>
	<name>Book Review: Building a Server with FreeBSD 7</name>
	<url>http://www.freesoftwaremagazine.com/articles/book_review_building_server_freebsd_7</url>
	<site-name>Free Software Magazine</site-name>
	<site-url>http://www.freesoftwaremagazine.com/</site-url>
	<date>7 July 2008</date>
	<author>Ken Leyba</author>
	<p>A review of the book &#34;Building a Server with FreeBSD 7&#34; by Bryan J.
	  Hong.</p>
      </story>

      <story>
	<name>Book Review: The Best of FreeBSD Basics</name>
	<url>http://www.osnews.com/story/19947/Book_Review:_The_Best_of_FreeBSD_Basics</url>
	<site-name>OS News</site-name>
	<site-url>http://www.osnews.com/</site-url>
	<date>2 July 2008</date>
	<author>Peter Hummers</author>
	<p>A review of the book &#34;The Best of FreeBSD Basics&#34;.</p>
      </story>
    </month>

    <month>
      <name>6</name>
      <story>
	<name>How FreeBSD makes vulnerability auditing easy: portaudit</name>
	<url>http://blogs.techrepublic.com.com/security/?p=477</url>
	<site-name>Tech Republic</site-name>
	<site-url>http://www.techrepublic.com.com/</site-url>
	<date>24 June 2008</date>
	<author>Chad Perrin</author>
	<p>An article that highlights the ease with which a FreeBSD
	  system can be kept upto-date with respect to vulnerabilities.</p>
      </story>

      <story>
        <name>Writing a kernel module for FreeBSD 7</name>
	<url>http://www.freesoftwaremagazine.com/articles/writing_a_kernel_module_for_freebsd</url>
	<site-name>Free Software Magazine</site-name>
	<site-url>http://www.freesoftwaremagazine.com/</site-url>
	<date>19 June 2008</date>
	<author>Yousef Ourabi</author>
	<p>A short introduction to building kernel modules on FreeBSD 7.</p>
      </story>
    </month>

    <month>
      <name>3</name>

      <story>
        <name>Review of FreeBSD 7</name>
	<url>http://www.freesoftwaremagazine.com/articles/review_of_freebsd_7</url>
	<site-name>Free Software Magazine</site-name>
	<site-url>http://www.freesoftwaremagazine.com/</site-url>
	<date>5 March 2008</date>
	<author>Yousef Ourabi</author>
	<p>A review of FreeBSD 7.0 Beta 3.</p>
      </story>
    </month>

    <month>
      <name>2</name>
      <story>
        <name>Faster Performance, Fewer Machines For FreeBSD?</name>
	<url>http://www.internetnews.com/dev-news/article.php/3731386/Faster+Performance+Fewer+Machines+For+FreeBSD.htm</url>
	<site-name>InternetNews.com</site-name>
	<site-url>http://www.internetnews.com/</site-url>
	<date>29 February 2008</date>
	<author>Sean Michael Kerner</author>
	<p>A brief look at FreeBSD 7.0.</p>
      </story>

      <story>
        <name>What's New in FreeBSD 7.0</name>
	<url>http://www.onlamp.com/pub/a/bsd/2008/02/26/whats-new-in-freebsd-70.html</url>
	<site-name>ONLamp.com</site-name>
	<site-url>http://www.onlamp.com/</site-url>
	<date>26 February 2008</date>
	<author>Federico Biancuzzi</author>
	<p>An interview with several FreeBSD developers about features in
	  FreeBSD 7.0-RELEASE.</p>
      </story>
    </month>

    <month>
      <name>1</name>

      <story>
        <name>DesktopBSD 1.6 Released</name>
        <url>http://www.osnews.com/story/19134/DesktopBSD_1.6_Released</url>
	<site-name>OSNews</site-name>
	<site-url>http://www.osnews.com/</site-url>
	<date>9 January 2008</date>
	<author>Thom Holwerda</author>
	<p>Version 1.6 of DesktopBSD has been released.  <a
            href="http://www.desktopbsd.net/">DesktopBSD</a> is a
          desktop operating system based on FreeBSD.</p>
      </story>
    </month>
  </year>

</press>
