=== freebsd/freebsd-doc/share/sgml/statusreport.dtd
<!-- $FreeBSD$ -->

<!ENTITY % xml.features "INCLUDE">
<!ENTITY % sgml.features "IGNORE">

<!ELEMENT report (date, section, category+, project+)>

<!ELEMENT date (month, year)>
<!ATTLIST date
  id		ID	#IMPLIED
>

<!ELEMENT month (#PCDATA)>
<!ATTLIST month
  id		ID	#IMPLIED
>

<!ELEMENT year (#PCDATA)>
<!ATTLIST year
  id		ID	#IMPLIED
>

<!ELEMENT section (title, p+)>
<!ATTLIST section
  id		ID	#IMPLIED
>

<!ELEMENT category (name, description)>
<!ATTLIST category
  id		ID	#IMPLIED
>

<!ELEMENT name (#PCDATA | given | common)*>
<!ATTLIST name
  id		ID	#IMPLIED
>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description
  id		ID	#IMPLIED
>

<!ELEMENT project (title, contact, links, body, help?)>
<!ATTLIST project
  id		ID	#IMPLIED
  cat		CDATA	#REQUIRED
>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
  id		ID	#IMPLIED
>

<!ELEMENT contact (person+)>
<!ATTLIST contact
  id		ID	#IMPLIED
>

<!ELEMENT person (name, email)>
<!ATTLIST person
  id		ID	#IMPLIED
>

<!ELEMENT given (#PCDATA)>
<!ATTLIST given
  id		ID	#IMPLIED
>

<!ELEMENT common (#PCDATA)>
<!ATTLIST common
  id		ID	#IMPLIED
>

<!ELEMENT email (#PCDATA)>
<!ATTLIST email
  id		ID	#IMPLIED
>

<!ELEMENT links (url+)?>
<!ATTLIST links
  id		ID	#IMPLIED
>

<!ELEMENT url (#PCDATA)>
<!ATTLIST url
  id		ID	#IMPLIED
  href		CDATA	#REQUIRED
>

<!ENTITY % mixed.inline "#PCDATA | a | br | p | strong | b | em | ul">

<!ELEMENT body (%mixed.inline;)*>
<!ATTLIST body
  id		ID	#IMPLIED
>

<!ELEMENT br EMPTY>

<!ELEMENT ul (li)+>
<!ATTLIST ul
  id		ID	#IMPLIED
>

<!ELEMENT li (%mixed.inline;)*>
<!ATTLIST li
  id		ID	#IMPLIED
>

<!ELEMENT p (%mixed.inline;)*>
<!ATTLIST p
  id		ID	#IMPLIED
>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
  id		ID	#IMPLIED
  href		CDATA	#REQUIRED
>

<!ELEMENT help (task)+>
<!ATTLIST help
  id		ID	#IMPLIED
>

<!ELEMENT task (#PCDATA)>
<!ATTLIST task
  id		ID	#IMPLIED
>

<!ENTITY % autogen.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Automatically Generated Entities//EN"
        "http://www.FreeBSD.org/XML/cwd/autogen.ent">
%autogen.ent;

<!ENTITY % iso8879.ent
 PUBLIC "-//FreeBSD//ENTITIES ISO 8879:1986 Entity Set//EN//XML"
        "http://www.FreeBSD.org/XML/www/share/sgml/iso8879.ent">
%iso8879.ent;

<!ENTITY % l10n.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Entities//EN"
        "http://www.FreeBSD.org/XML/www/share/sgml/l10n.ent">
%l10n.ent;

<!ENTITY % common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Common Entities//EN"
        "http://www.FreeBSD.org/XML/www/share/sgml/common.ent">
%common.ent;

=== freebsd/freebsd-doc/en_US.ISO8859-1/htdocs/news/status/report-2009-01-2009-03.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE report PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for Status
Report//EN"
"http://www.FreeBSD.org/XML/www/share/sgml/statusreport.dtd">
<!-- $FreeBSD$ -->
<report>
  <date>
    <month>January-March</month>

    <year>2009</year>
  </date>

  <section>
    <title>Introduction</title>

    <p>Since the last Status Reports there has been interesting progress
    in FreeBSD Development. FreeBSD 7.2 was released just a few days ago.
    Some of the highlights include: Support for superpages in the FreeBSD
    Virtual Memory subsystem. The FreeBSD Kernel Virtual Address space
    has been increased to 6GB on amd64. An updated jail(8) subsystem that
    supports multi-IPv4/IPv6/noIP and much more. Lots of FreeBSD
    Developers are in Ottawa, Canada attending the FreeBSD Developer
    Summit that is before BSDCan. BSDCan officially starts tomorrow and
    should cover lots of interesting topics, see the 
    <a href="http://www.bsdcan.org/2009/">BSDCan Website</a>

    for more information.</p>

    <p>Thanks to all the reporters for the excellent work! We hope you
    enjoy reading.</p>
  </section>

  <category>
    <name>proj</name>

    <description>Projects</description>
  </category>

  <category>
    <name>team</name>

    <description>FreeBSD Team Reports</description>
  </category>

  <category>
    <name>arch</name>

    <description>Architectures</description>
  </category>

  <category>
    <name>docs</name>

    <description>Documentation</description>
  </category>

  <category>
    <name>soc</name>

    <description>Google Summer of Code</description>
  </category>

  <project cat='team'>
    <title>FreeBSD BugBusting Team</title>

    <contact>
      <person>
        <name>
          <given>Mark</given>

          <common>Linimon</common>
        </name>

        <email>bugmeister@</email>
      </person>

      <person>
        <name>
          <given>Remko</given>

          <common>Lodder</common>
        </name>

        <email>bugmeister@</email>
      </person>
    </contact>

    <links>
      <url href="http://www.FreeBSD.org/support.html#gnats" />

      <url href="http://wiki.FreeBSD.org/BugBusting" />

      <url href="http://people.FreeBSD.org/~linimon/studies/prs/" />

      <url
      href="http://people.freebsd.org/~linimon/studies/prs/recommended_prs.html" />
    </links>

    <body>
      <p>We continue to classify PRs as they arrive, with 'tags'
      corresponding to the kernel subsystem, or man page references for
      userland PRs. These tags, in turn, produce lists of PRs sorted both
      
      <a
      href="http://people.freebsd.org/~linimon/studies/prs/pr_tag_index.html">
      by tag</a>

      and 
      <a
      href="http://people.freebsd.org/~linimon/studies/prs/pr_manpage_index.html">
      by manpage</a>
      </p>

      <p>Mark Linimon (linimon@) has created 
      <a href="http://people.freebsd.org/~linimon/annotated_prs.re.html">
      special reports for the Release Engineering Team</a>

      to help focus on regressions and other areas of interest relating
      to the release of FreeBSD 7.2 in the coming weeks. This is a
      refinement of the 
      <a
      href="http://people.freebsd.org/~linimon/annotated_prs.sample.html">
      'customized reports for developers'</a>

      announced in the last status report.</p>

      <p>A full list of all the 
      <a href="http://people.freebsd.org/~linimon/studies/prs/">
      automatically generated reports</a>

      is also available. Any recommendations for reports which do not
      currently exist but which would be beneficial are welcomed.</p>

      <p>Mark Linimon also continues attempting to define the general
      problem and investigating possible new work flow models, and will be
      presenting on the subject at BSDCan.</p>

      <p>The list of 
      <a
      href="http://people.freebsd.org/~linimon/studies/prs/recommended_prs.html">
      PRs recommended for committer evaluation</a>

      by the BugBusting team continues to receive new additions. This
      list contains PRs, mostly with patches, that the BugBusting team
      feel are probably ready to be committed as-is, or are probably
      trivially resolved in the hands of a committer with knowledge of
      the particular subsystem. All committers are invited to take a look
      at this list whenever they have a spare 5 minutes and wish to close
      a PR.</p>

      <p>Since the last status report, the number of open bugs
      continued to hover around the 5600 mark, although has began to rise
      with the 7.2 ports freeze.</p>

      <p>As always, more help is appreciated, and committers and
      non-committers alike are invited to join us on #freebsd-bugbusters
      on EFnet and help close stale PRs or commit patches from valid
      PRs.</p>
    </body>

    <help>
      <task>Try to find ways to get more committers helping us with
      closing PRs that the team has already analyzed.</task>

      <task>Think of some way for committers to only view PRs that have
      been in some way 'vetted' or 'confirmed'.</task>

      <task>Generate more publicity for what we've already got in place,
      and for what we intend to do next.</task>

      <task>Define new categories, classifications, and states for PRs,
      that will better match our work flow (in progress).</task>
    </help>
  </project>

  <project cat='proj'>
    <title>Clang replacing GCC in the base system</title>

    <contact>
      <person>
        <name>
          <given>Ed</given>

          <common>Schouten</common>
        </name>

        <email>ed@FreeBSD.org</email>
      </person>

      <person>
        <name>
          <given>Roman</given>

          <common>Divacky</common>
        </name>

        <email>rdivacky@FreeBSD.org</email>
      </person>

      <person>
        <name>
          <given>Brooks</given>

          <common>Davis</common>
        </name>

        <email>brooks@FreeBSD.org</email>
      </person>

      <person>
        <name>
          <given>Pawel</given>

          <common>Worach</common>
        </name>

        <email>pawel.worach@gmail.com</email>
      </person>
    </contact>

    <links>
      <url href="http://wiki.freebsd.org/BuildingFreeBSDWithClang">
      Building FreeBSD with Clang</url>

      <url href="http://git.hoeg.nl/?p=llvm-bmake">Clang patchset</url>

      <url href="http://clang.llvm.org/">Clang website</url>
    </links>

    <body>
      <p>The last 3-4 months we've been working together with the LLVM
      developers to discuss any bugs and issues we are experiencing with
      their Clang compiler frontend. The FreeBSD project is looking at
      the possibility to replace GCC with Clang as a system compiler. It
      can compile 99% of the FreeBSD world and can compile booting kernel
      on i386/amd64 but it still contains bugs and its C++ support is
      still immature.</p>

      <p>Ed is maintaining a patchset for the FreeBSD sources to replace
      cc(1) by a Clang binary and bootstrap almost all sources with the
      Clang compiler.</p>

      <p>The LLVM developers are very helpful fixing most of the bugs
      we've reported (over 100). Unfortunately we are currently blocked
      on some bug reports that prevent us from building libc, libm,
      libcrypto and various CDDL libraries with Clang but the FreeBSD
      kernel itself compiles and boots.</p>
    </body>

    <help>
      <task>Testing Clang with compilation of various applications and
      reporting bugs.</task>

      <task>Testing the llvm-bmake branch to find more bugs.</task>

      <task>Arranging an experimental ports build.</task>
    </help>
  </project>

  <project cat='docs'>
    <title>Hungarian Documentation Project</title>

    <contact>
      <person>
        <name>
          <given>Gábor</given>

          <common>Kövesdán</common>
        </name>

        <email>gabor@FreeBSD.org</email>
      </person>

      <person>
        <name>
          <given>Gábor</given>

          <common>Páli</common>
        </name>

        <email>pgj@FreeBSD.org</email>
      </person>
    </contact>

    <links>
      <url href="http://www.FreeBSD.org/hu">Hungarian Web Page for
      FreeBSD</url>

      <url href="http://www.FreeBSD.org/doc/hu">Hungarian Documentation
      for FreeBSD</url>

      <url href="http://wiki.FreeBSD.org/HungarianDocumentationProject">
      The FreeBSD Hungarian Documentation Project's Wiki Page</url>

      <url
      href="http://p4web.freebsd.org/@md=d&amp;cd=//depot/projects/docproj_hu/&amp;c=aXw@//depot/projects/docproj_hu/?ac=83">
      Perforce Depot for the FreeBSD Hungarian Documentation
      Project</url>
    </links>

    <body>
      <p>We are proud to announce that the FreeBSD Hungarian web pages
      have been extended by the following items:</p>

      <ul>
        <li>Project news entries, staring from 2009 (HTML, RSS, RDF)</li>

        <li>Press releases, starting from 2008 (HTML, RSS)</li>

        <li>Events, starting from 2009 (HTML, RSS)</li>

        <li>Security advisories (HTML, RSS)</li>
      </ul>

      <p>We are still hoping that having the 
      <a href="http://www.freebsd.org/doc/hu/books/fdp-primer/">FDP
      Primer</a>

      translated will encourage others to help our work. Feel free to
      contribute, every submitted line of translation or feedback is
      appreciated and is highly welcome. For more information on how to
      contribute, please read the project's 
      <a href="http://www.freebsd.org/hu/docproj/hungarian.html">
      introduction</a>

      (in Hungarian).</p>
    </body>

    <help>
      <task>Translate news entries, press releases.</task>

      <task>Translate Release Notes for -CURRENT and 8.X.</task>

      <task>Translate articles.</task>

      <task>Translate web pages.</task>

      <task>Read the translations, send feedback.</task>
    </help>
  </project>
