=== freebsd/freebsd-doc/share/xml/sitemap.dtd
<!-- $FreeBSD$ -->

<!ELEMENT sitemap (cvs:keyword?, term*, category*)>
<!ELEMENT term (text, destination)>

<!ELEMENT category (item*)>
<!ATTLIST category name CDATA #REQUIRED>

<!ELEMENT item (text, destination)>

<!ELEMENT text (#PCDATA)>
<!ELEMENT destination (#PCDATA)>

<!ENTITY % cvs
 PUBLIC "-//FreeBSD//DTD FreeBSD CVS Keywords//EN"
	"http://www.FreeBSD.org/XML/share/xml/cvs.dtd">
%cvs;

<!ENTITY % autogen.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Automatically Generated Entities//EN"
        "http://www.FreeBSD.org/XML/cwd/autogen.ent">
%autogen.ent;

<!ENTITY % iso8879.ent
 PUBLIC "-//FreeBSD//ENTITIES ISO 8879:1986 Entity Set//EN//XML"
        "http://www.FreeBSD.org/XML/share/xml/iso8879.ent">
%iso8879.ent;

<!ENTITY % l10n.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Language Specific Entities//EN"
        "http://www.FreeBSD.org/XML/lang/share/xml/l10n.ent">
%l10n.ent;
 
<!ENTITY % l10n-common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Language Specific Common Entities//EN"
        "http://www.FreeBSD.org/XML/share/xml/l10n-common.ent">
%l10n-common.ent;

<!ENTITY % release.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Release Entities//EN"
        "http://www.FreeBSD.org/XML/share/xml/release.ent">
%release.ent;

<!ENTITY % common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Common Entities//EN"
        "common.ent">
%common.ent;

=== freebsd/freebsd-doc/ru_RU.KOI8-R/htdocs/search/sitemap.xml
<?xml version="1.0" encoding="koi8-r"?>
<!DOCTYPE sitemap PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for Sitemap//EN"
        "http://www.FreeBSD.org/XML/share/xml/sitemap.dtd">

<!-- $FreeBSD$ -->

<sitemap>
  <term>
    <text>Alpha</text>
    <destination>&base;/platforms/alpha.html</destination>
  </term>

  <term>
    <text>Compaq Alpha</text>
    <destination>&base;/platforms/alpha.html</destination>
  </term>

  <term>
    <text>DEC Alpha</text>
    <destination>&base;/platforms/alpha.html</destination>
  </term>

  <term>
    <text>DIGITAL Alpha</text>
    <destination>&base;/platforms/alpha.html</destination>
  </term>

  <term>
    <text>FreeBSD/alpha</text>
    <destination>&base;/platforms/alpha.html</destination>
  </term>

  <term>
    <text>HP Alpha</text>
    <destination>&base;/platforms/alpha.html</destination>
  </term>

  <term>
    <text>AMD64</text>
    <destination>&base;/platforms/amd64.html</destination>
  </term>

  <term>
    <text>Athlon64</text>
    <destination>&base;/platforms/amd64.html</destination>
  </term>

  <term>
    <text>FreeBSD/amd64</text>
    <destination>&base;/platforms/amd64.html</destination>
  </term>

  <term>
    <text>Opteron</text>
    <destination>&base;/platforms/amd64.html</destination>
  </term>

  <term>
    <text>x86-64</text>
    <destination>&base;/platforms/amd64.html</destination>
  </term>

  <term>
    <text>Usage statistics for this server</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>Statistics for this server</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>WWW statistics for this server</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>Fieber, John</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>Apache http server</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>http server</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>WWW server www.FreeBSD.ORG</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>hub.freebsd.org</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>BSDi, network connection</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>Network connection, BSDi</text>
    <destination>../internal/about.html</destination>
  </term>

  <term>
    <text>Hittinger, Mark</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>WinNet Communications</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>Netscape Navigator</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>Java, Netscape Navigator</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>Internet services</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>X Windows workstation</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>Networking</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>Software development</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>Net surfing</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>Education and research</text>
    <destination>../applications.html</destination>
  </term>

  <term>
    <text>Security, Auditors</text>
    <destination>../auditors.html</destination>
  </term>

  <term>
    <text>Auditors</text>
    <destination>../auditors.html</destination>
  </term>

  <term>
    <text>busdma and SMPng driver conversion project</text>
    <destination>&base;/projects/busdma/index.html</destination>
  </term>

  <term>
    <text>SMPng driver conversion</text>
    <destination>&base;/projects/busdma/index.html</destination>
  </term>

  <term>
    <text>C99 &amp; POSIX Conformance Project</text>
    <destination>&base;/projects/c99/index.html</destination>
  </term>

  <term>
    <text>POSIX Conformance</text>
    <destination>&base;/projects/c99/index.html</destination>
  </term>

  <term>
    <text>Gallery, Commercial</text>
    <destination>../gallery/cgallery.html</destination>
  </term>

  <term>
    <text>Commercial, Gallery</text>
    <destination>../gallery/cgallery.html</destination>
  </term>

  <term>
    <text>Charter, Release Engineering Team</text>
    <destination>&base;/releng/charter.html</destination>
  </term>

  <term>
    <text>Release Engineering Team Charter</text>
    <destination>&base;/releng/charter.html</destination>
  </term>

  <term>
    <text>Commercial Vendors</text>
    <destination>../commercial/commercial.html</destination>
  </term>

  <term>
    <text>Vendors, commercial</text>
    <destination>../commercial/commercial.html</destination>
  </term>

  <term>
    <text>Commercial Vendors, Consulting</text>
    <destination>../commercial/consulting.html</destination>
  </term>

  <term>
    <text>Consulting, Commercial Vendors</text>
    <destination>../commercial/consulting.html</destination>
  </term>

  <term>
    <text>Commercial Vendors, Hardware</text>
    <destination>../commercial/hardware.html</destination>
  </term>

  <term>
    <text>Hardware, Commercial Vendors</text>
    <destination>../commercial/hardware.html</destination>
  </term>

  <term>
    <text>Commercial Vendors, Software</text>
    <destination>../commercial/software.html</destination>
  </term>

  <term>
    <text>Software, Commercial Vendors</text>
    <destination>../commercial/software.html</destination>
  </term>

  <term>
    <text>Commercial Vendors, Miscellaneous</text>
    <destination>../commercial/misc.html</destination>
  </term>

  <term>
    <text>Miscellaneous, Commercial Vendors</text>
    <destination>../commercial/misc.html</destination>
  </term>

  <term>
    <text>Donations</text>
    <destination>&base;/donations/index.html</destination>
  </term>

  <term>
    <text>BSD Daemon</text>
    <destination>../copyright/daemon.html</destination>
  </term>

  <term>
    <text>Daemon, BSD</text>
    <destination>../copyright/daemon.html</destination>
  </term>

  <term>
    <text>Nemeth, Evi</text>
    <destination>../copyright/daemon.html </destination>
  </term>

  <term>
    <text>Lassiter, John</text>
    <destination>../copyright/daemon.html</destination>
  </term>

  <term>
    <text>Hosokawa, Tatsumi</text>
    <destination>../copyright/daemon.html </destination>
  </term>

  <term>
    <text>McKusick, Marshall Kirk</text>
    <destination>../copyright/daemon.html </destination>
  </term>

  <term>
    <text>Charter, Doceng Team</text>
    <destination>&base;/internal/doceng.html</destination>
  </term>

  <term>
    <text>Doceng Team Charter</text>
    <destination>&base;/internal/doceng.html</destination>
  </term>

  <term>
    <text>Documentation Project, doceng</text>
    <destination>&base;/internal/doceng.html</destination>
  </term>

  <term>
    <text>Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Project, Documentation</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Goals, documentation</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>FAQ, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Handbook, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Contributing, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Submitting corrections, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Submitting new material, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>SGML, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Linuxdoc, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Docbook, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Guidelines, Documentation Project</text>
    <destination>../docproj/docproj.html</destination>
  </term>

  <term>
    <text>Documentation</text>
    <destination>../docs.html</destination>
  </term>

  <term>
    <text>Handbook</text>
    <destination>../docs.html</destination>
  </term>

  <term>
    <text>Events</text>
    <destination>&base;/events/events.html</destination>
  </term>

  <term>
    <text>Features</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>4.4BSD, A complete operating system</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>Berkeley, University of California</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>UCB</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>Computer Systems Research Group</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>CSRG</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>Merged virtual memory and filesystem buffer cache</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>virtual memory</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>buffer cache</text>
    <destination>../features.html</destination>
  </term>

  <term>
    <text>Compatibility, SCO</text>
    <destination>../features.html</destination>
  </term>
